### Particle swarm optimization (PSO)

Particle swarm optimization (PSO)is a computational method that optimizes a problem by iteratively trying to improve a candidate solution with regard to a given measure of quality. It solves a problem by having a population of candidate solutions, here dubbed particles, and moving these particles around in the search-space according to simple mathematical formulae over the particle's position and velocity. Each particle's movement is influenced by its local best known position, but is also guided toward the best known positions in the search-space, which are updated as better positions are found by other particles. This is expected to move the swarm toward the best solutions.

PSO is originally attributed to Kennedy, Eberhart and Shi (1995). (WIKI)

### Exercise

Parts of the code is not complete. It is marked as `##` in the code. You are supposed to fill in those codes.

In [1]:
import numpy as np
import math
import random

PSO parameters

In [2]:
D=3 #dimensions
Lb=0*np.ones(D) # Lower bounds
Ub=10*np.ones(D) # Upper bounds
N=10 #number of particles
wmax=0.9 #inertia weight max
wmin=0.4 #inertia weight min
c1=2.05 # acceleration factor
c2=2.05 # acceleration factor
max_iter=10

#### Objective Function 

Some simple objective functions. Choose one. For a start choose the first one. 

In [3]:
#objective function 1
D=2 # dimenssion
Lb=-5*np.ones(D) # Lower bounds
Ub=5*np.ones(D) # Upper bounds

def fun(X): #min is -6.3333
    x1=X[:,0]
    x2=X[:,1]
    
    out=np.power(x1,2)-x1*x2+np.power(x2,2)+2*(x1)+4*x2+3
    return out

In [4]:
#alternative function 2

D=3
Lb=-3*np.ones(D) # Lower bounds
Ub=3*np.ones(D) # Upper bounds

def fun(X): #min is 0.0 [2 2 2]
    x1=X[:,0]
    x2=X[:,1]   
    x3=X[:,2]   
    out=np.power(x1-2,2)+np.power(x2-2,2)+np.power(x3-2,2)
    return out

In [5]:
#objective function 3

D=3
Lb=0*np.ones(D) # Lower bounds
Ub=10*np.ones(D) # Upper bounds

## objective function to minimize with constraints

def fun(X):
    x1=X[:,0]
    x2=X[:,1]
    x3=X[:,2]

    fx=10*np.power((x1-1),2)+20*x1*x2+np.power((x3-3),2)
    con=np.zeros((2,N))
    pen=np.zeros(2)
    con[0]=x1+x2+x3-5
    con[1]=np.power(x1,2)+np.power(x2,2)-x3
    for i in range(len(con)):
        if(np.all(con[i]==0)):
            #print(con[i])
            pen[i]=0
        else:
            #print(con[i])
            pen[i]=1
    penalty=10000
    return fx +penalty*np.sum(pen)

### initialize particles

In [6]:
pos=np.zeros((N,D))

for i in range(N):
    for j in range(D):
        pos[i,j]=Lb[j]+(Ub[j]-Lb[j])*np.random.random();
vel=0.1*pos
pos

array([[5.97061586, 3.8125396 , 7.70566677],
       [0.94092715, 9.6867218 , 2.75958611],
       [8.02867797, 3.11870016, 5.60397729],
       [3.97585163, 2.60733515, 9.55210473],
       [7.88315382, 9.63158016, 8.67516106],
       [2.86826147, 2.04004511, 7.56851912],
       [3.76447872, 3.28489268, 5.53064093],
       [0.26426476, 1.74748525, 8.32507742],
       [1.02453637, 8.21883078, 5.20976857],
       [2.67614931, 1.85132994, 5.3719119 ]])

Evaluate the initial values

In [7]:
# initialization
out=np.zeros(N)

#Calculate F()
out=fun(pos)
print(out)

#This will not work because the array is not copied
#pbestval=out
#pbest=pos

#update pbest by simply making a copy
pbestval=np.copy(out)
pbest=np.copy(pos)

#get the min F() value
fminval=np.min(out)

#update gbest
index=np.argmin(out, axis=0) #get the index with min value
gbest=pbest[index]

print(out,index)
print(gbest, fminval)

[20724.47770759 20182.38268601 21001.58462322 20338.81456004
 22024.53007521 20172.80303248 20330.14574172 20043.00548845
 20173.29891814 20132.80943781]
[20724.47770759 20182.38268601 21001.58462322 20338.81456004
 22024.53007521 20172.80303248 20330.14574172 20043.00548845
 20173.29891814 20132.80943781] 7
[0.26426476 1.74748525 8.32507742] 20043.0054884502


In [8]:
#testing code, replacing with the smallest values
#Similar code is used for updating pbest with the min value

a=np.array([1,21,3,4])
b=np.array([3,4,91,82])
ar=np.where(a<b)
print(ar)
b[ar]=a[ar]
print(a,b)

(array([0, 2, 3], dtype=int64),)
[ 1 21  3  4] [1 4 3 4]


In [9]:
#for 1 run
it=1
while it<=max_iter:
    w=wmax-(it/max_iter)*(wmax-wmin)
    
    #compute function F() value
    ##fill in here
    out = fun(pos)

    #update best (min) pbest values
    ##fill in here .. see above
    for i in range(N):
        if out[i] < pbestval[i]:
            pbestval[i] = out[i]
            pbest[i,:] = pos[i,:]
    
    #update gbest values from all pbest
    ##fill in here 
    gbest_index = np.argmin(pbestval)
    gbest = pbest[gbest_index,:]

    #update velocity and position phase 
    for i in range(N):
        for j in range(D):
            
            #update the vel[] here
            ##fill in here
            r1, r2 = np.random.rand(), np.random.rand()
            vel[i,j] = w*vel[i,j] + c1*r1*(pbest[i,j] - pos[i,j]) + c2*r2*(gbest[j] - pos[i,j])

            #update position
            ##fill in here
            pos[i,j] += vel[i,j]

            #check bounds
            if(pos[i,j]<Lb[j]):
                pos[i,j]=Lb[j]
            elif (pos[i,j]>Ub[j]):
                pos[i,j]=Ub[j]
            
    it=it+1

#store the gbest 
f_ans=fun(np.expand_dims(gbest, axis=0))
f_gbest=gbest
print(f_ans,gbest)

[20010.02083741] [0.         0.         3.14435169]


### Complete program for Multiple runs

Wrap the entire pso algorithm into another external loop so that it runs multiple times. From the multiple times, we obtain the best global value. 

In [10]:
#need to initialize pso parameters as above
D=3 #dimensions

N=20 #number of particles
wmax=0.9 #inertia weight max
wmin=0.4 #inertia weight min
c1=2.05 # acceleration factor
c2=2.05 # acceleration factor
max_iter=333

#objective function need to be defined first
Lb = np.zeros(D)  # Lower bounds for each dimension
Ub = 10 * np.ones(D)  # Upper bounds for each dimension

runmax=20
pos=np.zeros((N,D))
f_ans=np.zeros(runmax)
f_gbest=np.zeros((runmax,D))
pbestval=np.zeros_like(out)
pbest=np.zeros_like(pos)

for run in (range(runmax)):
    
    #random  population initialization for pos[] and v[]
    ## fill in here
    pos = np.random.uniform(low=Lb, high=Ub, size=(N,D))
    vel = np.zeros((N,D))
    
    # calculate F() for the initial population
    ## fill in here
    out = fun(pos)
    
    #update pbest by simply making a copy
    ## fill in here
    pbestval = np.copy(out)
    pbest = np.copy(pos)
    
    # update gbest
    ## fill in here
    gbest = pbest[np.argmin(pbestval)]
    
    #iterate
    it=1
    while it<=max_iter:
        
        #calculate w 
        ##fill in here
        w = wmax - (it/max_iter) * (wmax - wmin)
        
        #compute F() 
        ##fill in here
        out = fun(pos)
        
        #update pbest values
        ##fill in here
        for i in range(N):
            if out[i] < pbestval[i]:
                pbestval[i] = out[i]
                pbest[i,:] = pos[i,:]
         
        #update gbest values
        ##fill in here
        index_best = np.argmin(pbestval)
        if pbestval[index_best] < fun(np.expand_dims(gbest, axis=0)):
            gbest = pbest[index_best,:]
        
        #update velocity and position 
        ##fill in here
        for i in range(N):
            for j in range(D):
                #update position
                ##fill in here
                r1, r2 = np.random.rand(), np.random.rand()
                vel[i,j] = w * vel[i,j] + c1 * r1 * (pbest[i,j] - pos[i,j]) + c2 * r2 * (gbest[j] - pos[i,j])
                pos[i,j] += vel[i,j]
                
                #check bounds
                ##fill in here
                if pos[i,j] < Lb[j]:
                    pos[i,j] = Lb[j]
                elif pos[i,j] > Ub[j]:
                    pos[i,j] = Ub[j]
                    
        it=it+1
    
    #outer loop for multiple runs
    
    f_ans[run]=fun(np.expand_dims(gbest, axis=0))
    f_gbest[run]=gbest
    print(f_ans[run],f_gbest[run])
    
bfun=np.min(f_ans)
brun=np.argmin(f_ans)
bestX=f_gbest[brun]
print(bfun,bestX,brun)

20000.0 [1.00000014 0.         3.0000001 ]
20000.0 [0.99999977 0.         2.99999942]
20000.0 [1.00000022 0.         3.00000044]
20000.0 [0.99999994 0.         2.99999868]
20000.0 [1.00000013 0.         2.99999932]
20000.0 [1.00000015 0.         2.99999875]
20000.0 [1.00000024 0.         2.99999913]
20010.0 [0.         1.34765534 3.00000016]
20010.0 [0.         0.         2.99999955]
20000.0 [1.00000008 0.         3.00000123]
20000.0 [0.99999964 0.         2.99999932]
20000.0 [1.00000001 0.         3.00000032]
20000.0 [1.0000003 0.        3.0000003]
20010.0 [0.        0.        3.0000008]
20010.0 [0.         5.87762392 3.00000124]
20000.0 [0.99999995 0.         2.99999939]
20010.0 [ 0.         10.          2.99999927]
20000.0 [1.00000008 0.         3.00000009]
20000.0 [1.00000013 0.         2.99999976]
20000.0 [0.9999999  0.         2.99999994]
20000.0 [1.00000014 0.         3.0000001 ] 0


### Task (optional)
1. Plot the movement of the particles after each iteration. Sections where you need to complete are marked as comments `##`

Hint:

Wrap the entire pso algorithm into a function:
    `def pso(0):`
    
In the pso function, after the position have been updated, put a `yield pos` statement into the code. This will allow the animation loop to obtain the `pos` array from the `pso()` without ending the `pso()` updating loop. 

Next create a generator for the `pso()` function:
    `gen=pso()`

In the animation loop, just before the `draw.circle(..)` statement, extract the `pos` value from the `pso()` function:
    `posn=nex(gen)`

In [11]:
import pygame
import numpy as np
from random import seed, random

#need to initialize pso parameters 

D=2 #dimensions
N=30 #number of particles
wmax=0.9 #inertia weight max
wmin=0.4 #inertia weight min
c1=2.05 # acceleration factor
c2=2.05 # acceleration factor
max_iter=100

# declare variables
out=np.zeros(N)
pos=np.zeros((N,D))
pbestval=np.zeros_like(out)
pbest=np.zeros_like(pos)

# init random pos and vel
Lb=-5*np.ones(D) # Lower bounds
Ub=5*np.ones(D) # Upper bounds
for i in range(N):
    for j in range(D):
        pos[i,j]=Lb[j]+(Ub[j]-Lb[j])*np.random.random();
vel=0.1*pos

#objective function need to be defined first
def fun(X): #min is -6.3333
    x1=X[:,0]
    x2=X[:,1]
    
    out=np.power(x1,2)-x1*x2+np.power(x2,2)+2*(x1)+4*x2+3
    return out

# iteration 1
#calculate F(X)
for i in range(N):
    out[i]=fun(np.expand_dims(pos[i], axis=0))

#init pbest
pbestval=np.copy(out)
pbest=np.copy(pos)
    
fminval=np.min(out)

#init gbest
index=np.argmin(out, axis=0)
gbest=pbest[index]    



def pso(): 
## put the entire pso algorithm here, only do the single run version
    # Initialize PSO parameters
    D = 2  # Dimensions
    N = 30  # Number of particles
    wmax = 0.9  # Inertia weight max
    wmin = 0.4  # Inertia weight min
    c1 = 2.05  # Acceleration factor
    c2 = 2.05  # Acceleration factor
    max_iter = 100

    # Initialize random position and velocity
    Lb = -5 * np.ones(D)  # Lower bounds
    Ub = 5 * np.ones(D)  # Upper bounds
    pos = np.random.uniform(low=Lb, high=Ub, size=(N, D))
    vel = 0.1 * pos

    # Initialize objective function values, pbest, and gbest
    out = fun(pos)
    pbestval = np.copy(out)
    pbest = np.copy(pos)
    gbest = pbest[np.argmin(pbestval)]

    for it in range(max_iter):
        w = wmax - (it / max_iter) * (wmax - wmin)
        
        for i in range(N):
            out[i] = fun(np.expand_dims(pos[i], axis=0))
            if out[i] < pbestval[i]:
                pbestval[i] = out[i]
                pbest[i,:] = pos[i,:]

        index_best = np.argmin(pbestval)
        if pbestval[index_best] < fun(np.expand_dims(gbest, axis=0)):
            gbest = pbest[index_best,:]

        for i in range(N):
            r1, r2 = np.random.rand(), np.random.rand()
            vel[i,:] = w * vel[i,:] + c1 * r1 * (pbest[i,:] - pos[i,:]) + c2 * r2 * (gbest - pos[i,:])
            pos[i,:] += vel[i,:]

            # Check and adjust bounds
            pos[i,:] = np.clip(pos[i,:], Lb, Ub)

        yield pos  # Yield the current position of particles

#create the generator 
## fill in here
gen = pso()

# animation loop!!
pygame.init()
# Set up the drawing window
screen = pygame.display.set_mode([500, 500])

clock = pygame.time.Clock()
# Run until the user asks to quit
running = True
while running:
    # Did the user click the window close button?
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False


    # Fill the background with white
    screen.fill((255, 255, 255))
    try:
        # obtain the position value from pso() using next(..), assign it to posn
        ## fill in here
        posn = next(gen)
        # Scale and translate positions for visualization
        posn_vis = ((posn + 5) / 10 * 500).astype(int)  # Adjust based on Lb, Ub, and screen size
        
        for i in range(N):
            # pygame.draw.circle(screen,(250,0,0), posn[i].astype(int), 6)      # CODE FROM PROF
            pygame.draw.circle(screen, (250, 0, 0), posn_vis[i], 6)
            
    except StopIteration:
        break

    # Flip the display
    pygame.display.flip()
    clock.tick(60)


# Done! Time to quit.
pygame.quit()

pygame 2.5.2 (SDL 2.28.3, Python 3.8.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
