# Python Starter 2

### Functional programming

In [1]:
def generate_five_adder():
    def _five_adder(num):
        return num + 5
    return _five_adder  #return a function that captures 5. This is called a closure

add_5 = generate_five_adder()
add_5(6)

11

In [2]:
def generate_adder(increment):
    def _adder(a):
        return a + increment #this time captures 'increment' when generate_adder is first called
    return _adder

add_3 = generate_adder(3)
add_3(10)

13

In [3]:
generate_adder(8)(5)

13

In [4]:
numbers = range(10)

[add_5(i) for i in numbers]

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [5]:
list(map(add_5, numbers))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [6]:
import sys

def my_max(data):
    # Start with the smallest possible number
    highest = -sys.float_info.max

    for x in data:
        if x > highest:
            highest = x

    return highest

my_max([2, 50, 10, -11, -5])

50

Lambda functions

In [7]:
func = lambda a, b, c: a + b + c
func('a','b','c')

'abc'

In [8]:
data = range(10)
list(map(lambda x: 2*x, data))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
from functools import reduce
def my_max(data): 
    return reduce(lambda a, b: a if a > b else b, data, sys.float_info.min)

my_max([2, 5, 10, -11, -5])

10

### Unpacking

In [10]:
a,b,c=1,2,3
a,b,c

(1, 2, 3)

Extended unpacking

In [11]:
a,*b,c=[1,2,3,4,5,6]
print(a,b,c)


1 [2, 3, 4, 5] 6


Swapping

In [12]:
a,b=1,2
a,b=b,a
a,b

(2, 1)

## List Comprehensions

 [expresion **for** item **in** list **if** conditional]

In [13]:
mylist = [i for i in range(10)]
print(mylist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [15]:
def some_function(a):
    return (a + 5) / 2
    
my_formula = [some_function(i) for i in range(10)]
print(my_formula)

[2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0]


In [16]:
filtered = [i for i in range(20) if i%2==0]
print(filtered)
# [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


Nested list comprehension

    [value
          for sublist in list
              for value in sublist]

In [17]:
[[j for j in range(3)] for i in range(4)]

[[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [18]:
[j for j in range(3) for i in range(4)]

[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]

In [19]:
s=[['h','e',],['l','p']]
print([j for j in s])
print([k for j in s for k in j])

[['h', 'e'], ['l', 'p']]
['h', 'e', 'l', 'p']


In [20]:
[x+y for x in ['a','b','c'] for y in ['1','2','3']]

['a1', 'a2', 'a3', 'b1', 'b2', 'b3', 'c1', 'c2', 'c3']

In [21]:
[[x+y for x in ['a','b','c']] for y in ['1','2','3']]

[['a1', 'b1', 'c1'], ['a2', 'b2', 'c2'], ['a3', 'b3', 'c3']]

Flattening

In [22]:
import itertools
a = [[1, 2], [3, 4], [5, 6]]
list(itertools.chain.from_iterable(a))

[1, 2, 3, 4, 5, 6]

In [23]:
a = [[1, 2], [3, 4], [5, 6]]
sum(a, [])

[1, 2, 3, 4, 5, 6]

In [24]:
a = [[1, 2], [3, 4], [5, 6]]
[x for l in a for x in l]

[1, 2, 3, 4, 5, 6]

In [25]:
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[x for l1 in a for l2 in l1 for x in l2]

[1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
a = [1, 2, [3, 4], [[5, 6], [7, 8]]]
flatten = lambda x: [y for l in x for y in flatten(l)] if type(x) is list else [x]
flatten(a)

[1, 2, 3, 4, 5, 6, 7, 8]

Zipping lists

In [27]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
print([z for z in zip(a, b)])


[(1, 'a'), (2, 'b'), (3, 'c')]


Unzipping

In [28]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
z=zip(a,b)

print([i for i in zip(*z)])

[(1, 2, 3), ('a', 'b', 'c')]


Stars - unpacking

In [29]:
n=[1,2,3,4,5]
m=[n,8,9]
star=[*n,8,9]
print(m,star)
print(*n,n)

[[1, 2, 3, 4, 5], 8, 9] [1, 2, 3, 4, 5, 8, 9]
1 2 3 4 5 [1, 2, 3, 4, 5]


Grouping

In [30]:
a = [0,1, 2, 3, 4, 5, 6,7,8,9]

# Using iterators
group_adjacent = lambda a, k: zip(*([iter(a)] * k))
z=group_adjacent(a, 2)
[i for i in z]


[(0, 1), (2, 3), (4, 5), (6, 7), (8, 9)]

Sliding windows

In [31]:
from itertools import islice
def n_grams(a, n):
    z = (islice(a, i, None) for i in range(n))
    return zip(*z)

a = [0,1, 2, 3, 4, 5, 6,7,8,9]
[i for i in n_grams(a, 3)]

[(0, 1, 2),
 (1, 2, 3),
 (2, 3, 4),
 (3, 4, 5),
 (4, 5, 6),
 (5, 6, 7),
 (6, 7, 8),
 (7, 8, 9)]

### Dictionary

Iterating over dictionary key and value pairs

In [32]:
m = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
for k, v in m.items():
    print ('{}: {}'.format(k, v))

a: 1
b: 2
c: 3
d: 4


Double star - unpacking

In [33]:
date_info = {'year': "2020", 'month': "01", 'day': "01"}
filename = "{year}-{month}-{day}.txt".format(**date_info) ##error if no **
filename

'2020-01-01.txt'

Merging dictionaries

In [34]:
dict1 = { 'a': 1, 'b': 2 }
dict2 = { 'b': 3, 'c': 4 }
merged = { **dict1, **dict2 }

print(merged)

{'a': 1, 'b': 3, 'c': 4}


Inverting a dictionary

In [35]:
m = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
zip(m.values(), m.keys())

mi = dict(zip(m.values(), m.keys()))
mi


{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

Dictionary comprehensions

In [36]:
m = {x: x ** 2 for x in range(5)}
m

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

Generators

In [37]:
g = (x ** 2 for x in range(10))
next(g)

0

In [38]:
next(g)

1

In [39]:
next(g)

4

### Named Tuples

In [41]:
# Bachroin
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __str__(self):
        return f"Point(x={self.x}, y={self.y})"

# Code from professor
p = Point(x=1.0, y=2.0)
print(p)
q=Point(x=3.0, y=4.0)
print(q)
print(p.x,p.y)

Point(x=1.0, y=2.0)
Point(x=3.0, y=4.0)
1.0 2.0


### Map

In [42]:
def upper(s):
    return s.upper()
    
mylist = list(map(upper, ['this', 'is','a','lower','case','sentence']))
print(mylist)

['THIS', 'IS', 'A', 'LOWER', 'CASE', 'SENTENCE']


## Numpy

Numpy allows vectorized operations that List can't provide. These "vectorized" operations are very fast. A NumPy array always contains just one datatype.

In [43]:
import numpy as np
my_array = np.array(range(5))
my_array

array([0, 1, 2, 3, 4])

In [44]:
List=[0, 1,2,3,4]
[elem + 5 for elem in List]
#can't do List+5

[5, 6, 7, 8, 9]

In [45]:
#Numpy array
my_array+5

array([5, 6, 7, 8, 9])

In [46]:
x = np.arange(0, 10, 0.1)  # Start, stop, step size
# y = list(range(0, 10, 0.1)) don't work for list
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [47]:
import math
values = np.linspace(0, math.pi, 100)
values

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

Create multi dimensional arrays

In [48]:
m=np.zeros([3, 4, 2])
m

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
y = m.reshape([2, 2, -1])
y

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [50]:
x = np.array(range(40))
y = x.reshape([4, 5, 2])
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [51]:
y[2:, :1, :]  # Last 2 axes, 1st row, all columns

array([[[20, 21]],

       [[30, 31]]])

In [52]:
y.transpose()

array([[[ 0, 10, 20, 30],
        [ 2, 12, 22, 32],
        [ 4, 14, 24, 34],
        [ 6, 16, 26, 36],
        [ 8, 18, 28, 38]],

       [[ 1, 11, 21, 31],
        [ 3, 13, 23, 33],
        [ 5, 15, 25, 35],
        [ 7, 17, 27, 37],
        [ 9, 19, 29, 39]]])

In [53]:
y.shape

(4, 5, 2)

By default, array operations are element-by-element. Arrays must match in all dimensions in order to be compatible:


In [54]:
np.arange(5) * np.arange(5)


array([ 0,  1,  4,  9, 16])

### Flattening

In [55]:
A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])

Flattened_X = A.flatten()
print(Flattened_X)

print(A.flatten(order="C"))
print(A.flatten(order="F"))
print(A.flatten(order="A"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [56]:
print(A.ravel())

print(A.ravel(order="A"))

print(A.ravel(order="F"))

print(A.ravel(order="A"))

print(A.ravel(order="K"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Broadcasting
The two arrays are said to be broadcast compatible if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

Ff one array has any Dimension 1, then the data is REPEATED to match the other.

    x= [1 2]
    y= [3
        4
        5]
        
    x+y=[1 2    [3 3
         1 2  +  4 4
         1 2]    5 5]


### Stacking

In [58]:
A = np.array([3, 4, 5])
B = np.array([1,9,0])

print(np.row_stack((A, B)))

print(np.column_stack((A, B)))
np.shape(A)

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


(3,)

In [59]:
x=np.array([[1,2]])
y=np.array([[3],[4],[5]])
x+y

array([[4, 5],
       [5, 6],
       [6, 7]])

### Newaxis

Numpy allows indexing with np.newaxis to temporarily create new one-length dimensions on the fly.

In [60]:
threebythree = np.arange(9).reshape(3, 3)
threebythree

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
threebythree[:, np.newaxis, :]

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [62]:
x = np.arange(10).reshape(2, 5)
y = np.arange(8).reshape(2, 2, 2)

In [63]:
x_dash = x[:, :, np.newaxis, np.newaxis]
x_dash.shape

(2, 5, 1, 1)

In [64]:
y_dash = y[:, np.newaxis, :, :]
y_dash.shape

(2, 1, 2, 2)

In [65]:
res = x_dash * y_dash
res.shape

(2, 5, 2, 2)

### Masking and Selections

Numpy defines operators like == and < to apply to arrays element by element.

In [66]:
m=np.array([[ 2,  1,  0, -1],
       [ 0,  0,  0,  0],
       [-2, -1,  0,  1]])

In [67]:
iszero = m == 0
iszero

array([[False, False,  True, False],
       [ True,  True,  True,  True],
       [False, False,  True, False]])

In [68]:
n=np.array([[ 2,  1,  9, -1],
       [ 9, 9,  9,  9],
       [-2, -1,  9,  1]])
n[iszero]

array([9, 9, 9, 9, 9, 9])

In [69]:
n[np.logical_not(iszero)]

array([ 2,  1, -1, -2, -1,  1])

In [70]:
n[iszero]=999
n

array([[  2,   1, 999,  -1],
       [999, 999, 999, 999],
       [ -2,  -1, 999,   1]])

### Where

In [71]:
a = np.array([[1, 5, 3], [4, 5, 6]]) 
print(a) 
  
b = np.where(a<4) 
print(a[b]) 

[[1 5 3]
 [4 5 6]]
[1 3]


In [72]:
a = np.arange(10)
np.where(a < 5, a, 10*a) # a>5 multiply by 10 else keep as a

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

References

In [73]:
x = np.arange(5)
y = x[:]
y[2] = 0 # y overrides x because y receives a reference to x
x

array([0, 1, 0, 3, 4])

In [74]:
# compare with Lists
x = list(range(5))
y = x[:]
y[2] = 0
x

[0, 1, 2, 3, 4]

In [75]:
x = np.arange(5)
y = np.copy(x[:]) # y gets a copy, so won't interfere with x
y[2] = 0 
x

array([0, 1, 2, 3, 4])

## Test Yourself



1. Divide two numpy arrays unless denominator is zero. Use list comprehension.

    `array1 = np.array([0, 1, 2])
    array2 = np.array([0, 1, 1])`

    array1 / array2 # should be np.array([0, 1, 2])

In [76]:
# Bachroin
import numpy as np

array1 = np.array([0, 1, 2])
array2 = np.array([0, 1, 1])

result = np.array([num / denom if denom != 0 else 0 for num, denom in zip(array1, array2)])

print(result)

[0. 1. 2.]


2. Merge two array with the smallest of two values. Use list comprehension.
    
    `a=np.array([1,21,3,4])
    b=np.array([3,4,91,82])`
    
    Result [1,4,3,4]

In [77]:
# Bachroin

import numpy as np

a = np.array([1, 21, 3, 4])
b = np.array([3, 4, 91, 82])

result = np.array([min(val_a, val_b) for val_a, val_b in zip(a, b)])

print(result)

[1 4 3 4]


3. `d=np.array([[0,10,12,11,14],
      [10,0,13,15,8],
      [12,13,0,9,14],
      [11,15,9,0,16],
      [14,8,14,16,0]])`

Obtain the 1/d, element-wise inverse, using list comprehension.



In [78]:
# Bachroin
import numpy as np

d = np.array([[0, 10, 12, 11, 14],
              [10, 0, 13, 15, 8],
              [12, 13, 0, 9, 14],
              [11, 15, 9, 0, 16],
              [14, 8, 14, 16, 0]])

inverse_d = np.array([[1/elem if elem != 0 else 0 for elem in row] for row in d])

print(inverse_d)

[[0.         0.1        0.08333333 0.09090909 0.07142857]
 [0.1        0.         0.07692308 0.06666667 0.125     ]
 [0.08333333 0.07692308 0.         0.11111111 0.07142857]
 [0.09090909 0.06666667 0.11111111 0.         0.0625    ]
 [0.07142857 0.125      0.07142857 0.0625     0.        ]]


4. Extract from the array `np.array([3,4,6,10,24,89,45,43,46,99,100])` with Boolean masking all the number

    a. which are not divisible by 3

    b. which are divisible by 5

    c. which are divisible by 3 and 5

In [79]:
# Bachroin
import numpy as np

arr = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])

# a. Numbers which are not divisible by 3
not_divisible_by_3 = arr[arr % 3 != 0]

# b. Numbers which are divisible by 5
divisible_by_5 = arr[arr % 5 == 0]

# c. Numbers which are divisible by 3 and 5
divisible_by_3_and_5 = arr[(arr % 3 == 0) & (arr % 5 == 0)]

print("Not divisible by 3:", not_divisible_by_3)
print("Divisible by 5:", divisible_by_5)
print("Divisible by 3 and 5:", divisible_by_3_and_5)

Not divisible by 3: [  4  10  89  43  46 100]
Divisible by 5: [ 10  45 100]
Divisible by 3 and 5: [45]


5. Write code that finds the distance between all coordinates without using any loops. 

```
Input= [[2,3,4],[1,2,3]]
Output =array([[0.        , 1.41421356, 2.82842712],
               [1.41421356, 0.        , 1.41421356],
               [2.82842712, 1.41421356, 0.        ]])
```



In [80]:
# Bachroin
import numpy as np

# Assuming corrected input
points = np.array([[0, 0], [1, 1], [2, 2]])

diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
# Calculate the squared distances
sq_distances = np.sum(diff ** 2, axis=-1)
# Take the square root to get the Euclidean distances
distances = np.sqrt(sq_distances)

print(distances)

[[0.         1.41421356 2.82842712]
 [1.41421356 0.         1.41421356]
 [2.82842712 1.41421356 0.        ]]


6. Given an numpy array of dimensions:

    `s=np.zeros((N,D))`
    
    Initialize `s` with random numbers between -4 and 4. You can use `np.random.random()`

In [81]:
# Bachroin
import numpy as np

N = 5  # Example dimension, you can set N and D to whatever you need
D = 3  # Example dimension

# Initialize s with random numbers between -4 and 4
s = np.random.random(size=(N, D)) * 8 - 4

print(s)

[[ 1.2667233   2.07292073  0.51073997]
 [ 0.20581077  3.21831676  0.24548716]
 [ 2.61649619  0.48776031  2.53831373]
 [-3.48611408 -0.84326776  1.98072576]
 [ 2.89296248  2.0301779  -0.27423792]]


### Done (Bachroin)