## Code in Lectures

### For-Loops

In [1]:
for value in range(5):
    print(value)

0
1
2
3
4


In [3]:
for value in range(3,5):
    print(value)

3
4


In [2]:
odd_numbers=[1,3,5,7,9]
even_numbers=[10,4,6,7,2]
for i in range(len(odd_numbers)):
    print(odd_numbers[i]+even_numbers[i])

11
7
11
14
11


In [6]:
T=[(1,2),(3,4),(5,6)]
for (a,b) in T:
    print(a,b)

1 2
3 4
5 6


### Zip and Enumerate

In [7]:
## FOR using ZIP

name=['Bob','Sam','Max']
age=[25,35,30]
for x,y in zip(name,age): #zip ties any list together and loops them in pairs
    print(x,y)

Bob 25
Sam 35
Max 30


In [8]:
## FOR using ENUMERATE

colors=['red','green','blue']
for index, value in enumerate(colors): #enumerates adds in an index
    print(index,value)

0 red
1 green
2 blue


In [13]:
colors=['red','green','blue']
for index, value in enumerate(colors): #enumerates adds in an index
    test_bachroin = index, value
    print(test_bachroin)

# Bachroin
# This output is of the 'Tuple' type, which is 'immutable'. This means that once the Tuple is created, its content or size cannot be changed.

(0, 'red')
(1, 'green')
(2, 'blue')


In [16]:
colors=['red','green','blue']
for index, value in enumerate(colors): #enumerates adds in an index
    test_bachroin = [index, value]
    print(test_bachroin)

# Bachroin
# This output is of the 'List' type, which is 'mutable'. This means that once the List is created, its content or size can be changed.

[0, 'red']
[1, 'green']
[2, 'blue']


In [9]:
for x,y,c in zip(name,age,colors): #zip ties any list together and loops them in pairs
    print(x,y,c)

Bob 25 red
Sam 35 green
Max 30 blue


### Lambda Functions 
functions without names only has a function body (procedure)

In [18]:
doubler = lambda x: x*2
print(doubler(6))

# Bachroin
# Maksudnya = 
# Fungsi lambda adalah fungsi anonim, yang berarti dia tidak dideklarasikan dengan kata kunci "def"
# fungsi lambda didefinisikan menggunakan kata kunci 'lambda' dan tidak memiliki nama.
# fungsi lambda tsb yang mengambil satu argumen x dan mengembalikan x*2

# jika contoh fungsi yg pake nama sperti ini=
# def doubler(x):
#   return x * 2

# Di Python, lambda itu bukan nama fungsi, 
# Tapi kata kunci yang digunakan untuk mendefinisikan fungsi anonim (tanpa nama). 
# Fungsi anonim lambda berguna untuk fungsi sederhana yang dapat ditulis dalam satu baris.

12


In [22]:
print((lambda x:x*2)(3))

# Bachroin
# Function Call: Setelah fungsi lambda didefinisikan, 
# (...)(3) menunjukkan bahwa fungsi tersebut  dipanggil dengan nilai 3 sebagai argumennya. 

6


### List comprehension

In [23]:
L=[x**2 for x in range(5)] # creates a list
print(L)

[0, 1, 4, 9, 16]


In [24]:
#using loops instead of comprehension
L=[]
for x in range(5):
    L.append(x**2)
print(L)

# Bachroin
# append() digunakan untuk menambahkan satu item ke akhir list. 

[0, 1, 4, 9, 16]


In [25]:
vec=[-4,-2,0,2,4]
L=[abs(x) for x in vec]
print(L)

[4, 2, 0, 2, 4]


In [26]:
L=[(x,x**2) for x in range(4) ] #creates tuples in a list
print(L)

[(0, 0), (1, 1), (2, 4), (3, 9)]


In [27]:
L=[x for x in vec if x>=0]
print(L)

[0, 2, 4]


In [28]:
L=[x if (x>=0) else 0 for x in vec ]
print(L)

[0, 0, 0, 2, 4]


### Nested Comprehension

In [29]:
vector=[[1,2,3],[4,5,6],[7,8,9]]
L= [number for lists in vector for number in lists] #don't use list!!
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
# Equivalent to 2 for-loops
L=[]
for lists in vector:
    for number in lists:
        L.append(number)
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
L=[[row[i] for row in matrix] for i in range(3)] # for each i, go through each row
print(L)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


### Map and Filter

In [32]:
L=list(map(ord,'food'))
print(L)

[102, 111, 111, 100]


In [33]:
L=list(filter((lambda x:x%2 ==0 ), range(10)))
print(L)

[0, 2, 4, 6, 8]


In [34]:
flat=lambda l: [item for sublist in l for item in sublist]
L=[[1,2,3],[3,5],[9,0,1]]
print(flat(L))

[1, 2, 3, 3, 5, 9, 0, 1]


### Dictionary Comprehension

In [35]:
L=['ReD','GrEeN','BlUe']
D={c.lower():c.upper() for c in L}
print(D)

{'red': 'RED', 'green': 'GREEN', 'blue': 'BLUE'}


In [36]:
D={c:c*3 for c in 'RED'}
print(D)

{'R': 'RRR', 'E': 'EEE', 'D': 'DDD'}


In [37]:
D={0:'A',1:'B',2:'C',3:'D'}
selectedKeys=[0,2]
X={k:D[k] for k in selectedKeys}
print(X)

{0: 'A', 2: 'C'}


In [38]:
removeKeys=[1]
X={k:D[k] for k in D.keys()-removeKeys}
print(X)

{0: 'A', 2: 'C', 3: 'D'}


In [39]:
D={0:'red','1':'green',2:'blue'}
R={v:k for k,v in D.items()}
print(R)

{'red': 0, 'green': '1', 'blue': 2}


In [40]:
L=['ReD','GrEeN','BlUe']
D={k:v for k,v in enumerate(L)}
print(D)

{0: 'ReD', 1: 'GrEeN', 2: 'BlUe'}


In [41]:
keys=['RED','GREEN','BLUE']
D={k:0 for k in keys}
print(D)

{'RED': 0, 'GREEN': 0, 'BLUE': 0}


In [42]:
keys=['name','age','job']
values=['bob',25,'dev']
D={k:v for (k,v) in zip(keys,values)}
print(D)

{'name': 'bob', 'age': 25, 'job': 'dev'}


In [43]:
D=dict(zip(keys,values))
print(D)

{'name': 'bob', 'age': 25, 'job': 'dev'}


In [44]:
D={x:x**2 for x in range(6) if x%2==0}
print(D)

{0: 0, 2: 4, 4: 16}


In [45]:
D={(k,v): k+v for k in range(2) for v in range(2)}
print(D)

{(0, 0): 0, (0, 1): 1, (1, 0): 1, (1, 1): 2}


### Dictionary with Lambda

In [46]:
exponent={'square': lambda x: x**2, 'cube': lambda x: x**3}
print(exponent['square'](3))

9


In [47]:
L=['a','b','c','d','e','f','g','h','i']
print(L[2:-5])

['c', 'd']


In [48]:
print(L[6:1:-2])
print(L[::-1])

['g', 'e', 'c']
['i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']


In [49]:
print(L[-1])

i


In [50]:
I=[1,2,3]
L[:0]=I
print(L)


[1, 2, 3, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']


In [51]:
L[len(L):]=I
print(L)

[1, 2, 3, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 1, 2, 3]


### String slicing

In [52]:
S='ABCDEFGHI'
print(S[6:1:-2])

GEC


## NUMPY

In [53]:
import numpy as np
np.empty(2)

array([-3.04492664e+50,  5.58585935e-37])

In [54]:
np.empty([2,3])

array([[4.67291993e-307, 2.33645827e-307, 4.45047026e-307],
       [2.11394918e-307, 3.33773471e-307, 4.45036841e-307]])

In [55]:
mylist=[1,2,3,4]
myarray=np.array(mylist)
print(myarray)

[1 2 3 4]


In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [59]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [60]:
list1=[1,2,3,4]
list2=[11,22,33,44]
myarray=np.array([list1,list2])
print(myarray)

[[ 1  2  3  4]
 [11 22 33 44]]


In [61]:
myarray.shape

(2, 4)

In [62]:
list1+list2

[1, 2, 3, 4, 11, 22, 33, 44]

In [63]:
myarray+myarray

array([[ 2,  4,  6,  8],
       [22, 44, 66, 88]])

In [64]:
height=[1.73,1.68,1.71]
weight=[65.4,59.2,63.6]
nph=np.array(height)
npw=np.array(weight)
BMI=npw/nph**2
BMI

array([21.85171573, 20.97505669, 21.75028214])

SubSet

In [65]:
BMI[BMI>21.]

array([21.85171573, 21.75028214])

Reshape

In [66]:
arr=np.arange(50).reshape(-1,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

### Iterables

In [67]:
iterobj=iter([1,2,3,4])
next(iterobj)


1

In [68]:
next(iterobj)


2

In [69]:
next(iterobj)

3

### Generators

In [70]:
def mygen():
    yield 10
    yield 20
    yield 40
gen=mygen()
print(next(gen))

10


In [71]:
print(next(gen))

20


In [72]:
print(next(gen))

40


In [73]:
def mygen2():
    n=1
    yield n
    n+=2
    yield n
    n+=3
    yield n
    yield 'End'
for n in mygen2():
    print(n)

1
3
6
End


### Done (Bachroin)