### Boids 
Boids is an artificial life simulation originally developed by Craig Reynolds. The aim of the simulation was to replicate the behavior of flocks of birds. Instead of controlling the interactions of an entire flock, however, the Boids simulation only specifies the behavior of each individual bird.

In [1]:
import numpy as np

In [2]:
n_boids=20

In [3]:
window_size=[600,600] #display window limit

In [4]:
position=np.random.rand(2, n_boids)*250 #random number less than 250
position.astype(int) #convert to integer
print(position)
print(position[:,1]) # print the second column

[[  8.99939047 179.02220197 214.36115125  39.08484425 118.39750774
  190.57712912  96.19427868 103.07213475 146.38136908  20.99455216
  183.91193066 171.55986693 119.27065205   3.97081584  24.75541419
  182.41912737  67.91793981  20.56044453 232.64264561  21.52595058]
 [159.95942562 203.97041688 231.95083435   4.93223235 124.03825486
  231.59483633 214.65398631 197.12716755   5.17484585  56.58436265
   82.79823824  77.04452613 136.73863556  58.95385365 138.69263023
  140.66584358  61.70915132 185.50027019 104.57167902 113.44988123]]
[179.02220197 203.97041688]


We set the random velocities within some limits. 

In [5]:
Lb=np.array([-2,-2]) #lower bound variables
Ub=np.array([2,2]) 
diff=Ub-Lb
print(diff)
velocity=Lb[:, np.newaxis]+np.random.rand(2,n_boids)*diff[:,np.newaxis] 
velocity

[4 4]


array([[ 1.45734854,  0.2021387 , -0.27213025, -1.31406111, -1.47388176,
        -1.01558758,  1.84303091,  1.70231653, -0.71782695,  1.1922122 ,
         1.51253707, -0.77309901,  0.60389469,  1.34508677, -0.49311984,
        -0.20249646, -1.48959667, -1.19641243, -1.60118993, -1.72937549],
       [-1.13536879,  0.96304839, -1.54089842, -1.23140916, -0.59168716,
        -0.87476001,  1.94023981, -1.45405673, -0.90204292, -0.85787807,
         0.29844458, -1.82330992, -0.56024187, -1.28213932, -1.24842216,
        -1.24457611,  0.55844299, -0.96505794, -0.8922738 , -0.77341029]])

`np.newaxis` creates a new index. Print them out to see why

In [6]:
np.random.rand(2,n_boids)

array([[0.18143653, 0.19435399, 0.25993924, 0.97164826, 0.93638017,
        0.68229758, 0.8403578 , 0.12880676, 0.16990869, 0.37480133,
        0.14420327, 0.00752486, 0.18114102, 0.01122793, 0.64700193,
        0.47151789, 0.99796196, 0.92796439, 0.17870119, 0.02011378],
       [0.28455744, 0.5089542 , 0.13222059, 0.77556949, 0.7988052 ,
        0.46520942, 0.88063505, 0.62713655, 0.41328508, 0.73409809,
        0.05751538, 0.56236171, 0.83672232, 0.5068594 , 0.08963139,
        0.56191131, 0.85272311, 0.28244695, 0.96399944, 0.44943008]])

In [7]:
diff[:,np.newaxis] 

array([[4],
       [4]])

In [8]:
position=position+velocity
pos=np.array(position.astype(int)) # we require integer coordinates
pos

array([[ 10, 179, 214,  37, 116, 189,  98, 104, 145,  22, 185, 170, 119,
          5,  24, 182,  66,  19, 231,  19],
       [158, 204, 230,   3, 123, 230, 216, 195,   4,  55,  83,  75, 136,
         57, 137, 139,  62, 184, 103, 112]])

We want to check if the position exceeds the window limit, if so, reverse the velocity. Complete the code below.

In [9]:
velocity[0]=[-1*v if p > window_size[0] else v for p,v in zip(pos[0],velocity[0])]
#velocity[1]= ..  #complete this 
print(velocity)
# check that limits are not exceeded

[[ 1.45734854  0.2021387  -0.27213025 -1.31406111 -1.47388176 -1.01558758
   1.84303091  1.70231653 -0.71782695  1.1922122   1.51253707 -0.77309901
   0.60389469  1.34508677 -0.49311984 -0.20249646 -1.48959667 -1.19641243
  -1.60118993 -1.72937549]
 [-1.13536879  0.96304839 -1.54089842 -1.23140916 -0.59168716 -0.87476001
   1.94023981 -1.45405673 -0.90204292 -0.85787807  0.29844458 -1.82330992
  -0.56024187 -1.28213932 -1.24842216 -1.24457611  0.55844299 -0.96505794
  -0.8922738  -0.77341029]]


In [10]:
velocity[0]=[-1*v if p < 0 else v for p,v in zip(pos[0],velocity[0])]
#velocity[1]=   # complete this
print(velocity)
# check that limits are not exceeded

[[ 1.45734854  0.2021387  -0.27213025 -1.31406111 -1.47388176 -1.01558758
   1.84303091  1.70231653 -0.71782695  1.1922122   1.51253707 -0.77309901
   0.60389469  1.34508677 -0.49311984 -0.20249646 -1.48959667 -1.19641243
  -1.60118993 -1.72937549]
 [-1.13536879  0.96304839 -1.54089842 -1.23140916 -0.59168716 -0.87476001
   1.94023981 -1.45405673 -0.90204292 -0.85787807  0.29844458 -1.82330992
  -0.56024187 -1.28213932 -1.24842216 -1.24457611  0.55844299 -0.96505794
  -0.8922738  -0.77341029]]


Create a function that calculates the distance between to position. Use the Euclidean metric to calculate. Complete the code below. Use `np.sqrt` to calculate square root.

In [11]:
def dist(position,i,j):
    #xdiff = 
    #ydiff = 
    #distance = 
    return distance

### Three Flocking Rules

1. Cohesion
1. Repulsion
1. Alignment

    Cohesion
	PROCEDURE rule1(boid bJ)

		Vector pcJ

		FOR EACH BOID b
			IF b != bJ THEN
				pcJ = pcJ + b.position
			END IF
		END

		pcJ = pcJ / N-1

		RETURN (pcJ - bJ.position) / 100

	END PROCEDURE
    
    Repulsion
    PROCEDURE rule2(boid bJ)

		Vector c = 0;

		FOR EACH BOID b
			IF b != bJ THEN
				IF |b.position - bJ.position| < 100 THEN
					c = c - (b.position - bJ.position)
				END IF
			END IF
		END

		RETURN c

	END PROCEDURE
    
    Alignment
    PROCEDURE rule3(boid bJ)

		Vector pvJ

		FOR EACH BOID b
			IF b != bJ THEN
				pvJ = pvJ + b.velocity
			END IF
		END

		pvJ = pvJ / N-1

		RETURN (pvJ - bJ.velocity) / 8

	END PROCEDURE

All the return vector values should be normalized using `np.linalg.norm`

see http://www.kfish.org/boids/pseudocode.html

In [12]:
# cohesion
def cohesion(j):
    cx=0
    cy=0
    count=0
    for i in range(n_boids):
        if (j!=i):
            distance=dist(position,i,j)
            if(distance<5):
                count=count+1
                cx=cx+position[0,i]
                cy=cy+position[1,i]
                
    if(count>0):
        cx=cx/count
        cy=cy/count
        
    rx=cx-position[0,j]
    ry=cy-position[1,j]
    norm=np.linalg.norm([rx,ry])
    if(norm>0):
        rx=rx/norm
        ry=ry/norm
    #print(rx,ry)
    return (rx,ry)

In [13]:
# repulsion
def repulsion(j):
    px=0
    py=0
    for i in range(n_boids):
        if (j!=i):
            distance=dist(position,i,j)
            if(distance < 10):
                # fill in here
                # file in here
    norm=np.linalg.norm([px,py])            
    if(norm>0):
        px=px/norm
        py=py/norm
    #print(px,py)
    return (px,py)

IndentationError: expected an indented block (2409293397.py, line 11)

In [ ]:
# alignment
def alignment(j):
    vx=0
    vy=0
    count=0
    for i in range(n_boids):
        if(j!=i):
            distance=dist(position,i,j)
            if(distance<20):
                count=count+1
                #fill in here
                #fill in here
    if(count>0):
        vx=vx-velocity[0,j]/count
        vy=vy-velocity[1,j]/count
        
    norm=np.linalg.norm([vx,vy])
    if(norm>0):
        vx=vx/norm
        vy=vy/norm
    return (vx,vy)

### Put all in a game loop

In [ ]:
import pygame
pygame.init()

#Try various values until works 
#A=
#B=
#C=

# Set up the drawing window
screen = pygame.display.set_mode(window_size)

# Run until the user asks to quit
running = True
while running:

    # Did the user click the window close button?
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # Fill the background with white
    screen.fill((255, 255, 255))
    pos=position.astype(int) # convert to integers
    
        
    for i in range(n_boids):
        pygame.draw.circle(screen, (0, 0, 255), pos[:,i], 5)
    
    if(np.random.random()<0.001):
        A=A*-1
        C=C*-1
    
    for i in range(n_boids): #individual updates
        v1x,v1y=cohesion(i)
        v2x,v2y=repulsion(i)
        v3x,v3y=alignment(i)

        velocity[0,i]+=A*v1x+B*v2x+C*v3x
        velocity[1,i]+=A*v1y+B*v2y+C*v3y
        
        velocity[0,i]=velocity[0,i]/np.linalg.norm([velocity[0,i],velocity[1,i]])
        velocity[1,i]=velocity[1,i]/np.linalg.norm([velocity[0,i],velocity[1,i]])
        
        position[0,i]+=velocity[0,i]
        position[1,i]+=velocity[1,i]
        #print(position)
    
    
    #check if position exceeds limit
    velocity[0]=[-1*v if p > window_size[0] else v for p,v in zip(position[0],velocity[0])]
    velocity[1]=[-1*v if p > window_size[1] else v for p,v in zip(position[1],velocity[1])]
    velocity[0]=[-1*v if p < 0 else v for p,v in zip(position[0],velocity[0])]
    velocity[1]=[-1*v if p < 0 else v for p,v in zip(position[1],velocity[1])]
    
    position[0]=[1 if p < 0 else p for p in position[0]]
    position[1]=[1 if p < 0 else p for p in position[1]]

    position[0]=[window_size[0]-1 if p > window_size[0] else p for p in position[0]]
    position[1]=[window_size[1]-1 if p > window_size[1] else p for p in position[1]]
    
    # Flip the display
    pygame.display.flip()

# Done! Time to quit.
pygame.display.quit()

### Try it Yourself
1. Change the values A,B and C. Slight changes will change the behavior quite unpredictably